# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='category.Category'),
        ),
    ]
