# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20171031_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created'], 'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': '\u041f\u043e\u0441\u0442', 'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
